
import { genesis } from './factory';
import { compute, modify } from './hash';
import { commit } from './flow';
import { flatten } from './space';
import { Side } from './types';

/**
 * @description  The Opening Book (Thư Viện Khai Cuộc - Bách Khoa Toàn Thư).
 * @purpose      Provide instant, Grandmaster-level opening moves.
 * @technique    Runtime Replay.
 * @content      The "18 Weapons" of Xiangqi (Thập Bát Ban Võ Nghệ).
 */

const BOOK = new Map<bigint, number>();

// =============================================================================
// SECTION 1: PERMANENT KNOWLEDGE (TRÍ THỨC VĨNH CỬU)
// =============================================================================
const KNOWLEDGE: Record<string, number> = {
    // Generated by Auditor/Tuner
};

// =============================================================================
// SECTION 2: PROCEDURAL OPENINGS (METADATA EXPORT)
// =============================================================================

export interface Opening {
    name: string;
    group: string;
    desc: string;
    moves: number[][]; // [fx, fy, tx, ty][]
}

export const OPENINGS: Opening[] = [
    // GROUP A: TRUNG PHÁO
    {
        name: "Bình Phong Mã Hiện Đại",
        group: "TRUNG PHÁO",
        desc: "Đỏ công trung lộ, Đen lên Mã và Tốt 3/7 phản công.",
        moves: [
            [7, 7, 4, 7], [1, 0, 2, 2], [1, 9, 2, 7], [7, 0, 6, 2],
            [8, 9, 7, 9], [0, 0, 1, 0], [2, 6, 2, 5], [2, 3, 2, 4],
            [7, 9, 7, 5], [1, 2, 0, 2], [7, 5, 3, 5], [0, 2, 0, 3]
        ]
    },
    {
        name: "Ngũ Thất Pháo",
        group: "TRUNG PHÁO",
        desc: "Biến thể công phá chốt 3 của đối phương.",
        moves: [
            [7, 7, 4, 7], [1, 0, 2, 2], [1, 9, 2, 7], [7, 0, 6, 2],
            [8, 9, 7, 9], [0, 0, 1, 0], [2, 6, 2, 5], [2, 3, 2, 4],
            [1, 7, 2, 7], [1, 2, 0, 2], [7, 9, 7, 8], [0, 3, 0, 4]
        ]
    },
    {
        name: "Phản Cung Mã",
        group: "TRUNG PHÁO",
        desc: "Đen đưa Pháo vào trong Mã, tạo bẫy phản công.",
        moves: [
            [7, 7, 4, 7], [1, 0, 2, 2], [1, 9, 2, 7], [1, 2, 3, 2],
            [8, 9, 7, 9], [7, 0, 6, 2], [7, 9, 7, 5], [3, 2, 4, 4]
        ]
    },
    {
        name: "Đơn Đề Mã",
        group: "TRUNG PHÁO",
        desc: "Lối đánh cổ điển, một Mã giữ trung, một Mã biên.",
        moves: [
            [7, 7, 4, 7], [1, 0, 2, 2], [1, 9, 2, 7], [0, 0, 1, 0],
            [8, 9, 7, 9], [7, 0, 8, 2], [1, 7, 3, 7], [3, 0, 4, 1]
        ]
    },

    // GROUP B: ĐỐI CÔNG PHÁO
    {
        name: "Thuận Pháo (Xe Chậm)",
        group: "ĐỐI CÔNG",
        desc: "Hai bên cùng vào Pháo đầu. Đánh trực diện.",
        moves: [
            [7, 7, 4, 7], [7, 2, 4, 2], [1, 9, 2, 7], [7, 0, 6, 2],
            [8, 9, 7, 9], [0, 0, 1, 0], [2, 6, 2, 5], [2, 3, 2, 4],
            [2, 7, 2, 5]
        ]
    },
    {
        name: "Thuận Pháo (Hoành Xe)",
        group: "ĐỐI CÔNG",
        desc: "Xe lên một nước rồi bình ngang kiểm soát lộ.",
        moves: [
            [7, 7, 4, 7], [7, 2, 4, 2], [1, 9, 2, 7], [7, 0, 6, 2],
            [8, 9, 8, 8], [0, 0, 1, 0], [8, 8, 2, 8], [1, 2, 1, 1]
        ]
    },
    {
        name: "Nghịch Pháo",
        group: "ĐỐI CÔNG",
        desc: "Pháo đối phương vào trung lộ ngược chiều.",
        moves: [
            [7, 7, 4, 7], [1, 2, 4, 2], [1, 9, 2, 7], [7, 0, 6, 2],
            [8, 9, 7, 9], [0, 0, 1, 0], [7, 9, 7, 5], [2, 3, 2, 4]
        ]
    },

    // GROUP C: PHONG CÁCH TỰ NHIÊN
    {
        name: "Phi Tượng Cuộc",
        group: "NHU ĐẠO",
        desc: "Lên Tượng đầu tiên. Dĩ nhu khắc cương.",
        moves: [
            [2, 9, 4, 7], [7, 2, 4, 2], [1, 9, 2, 7], [1, 0, 2, 2],
            [8, 9, 7, 9], [0, 0, 1, 0], [0, 9, 1, 7]
        ]
    },
    {
        name: "Tiên Nhân Chỉ Lộ",
        group: "NHU ĐẠO",
        desc: "Tấn Tốt thăm dò hư thực đối phương.",
        moves: [
            [2, 6, 2, 5], [6, 3, 6, 4], [1, 9, 2, 7], [7, 2, 5, 2],
            [7, 7, 2, 7], [1, 0, 2, 2], [0, 9, 1, 7], [7, 0, 6, 2]
        ]
    },

    // GROUP D: ĐẶC BIỆT
    {
        name: "Thiết Hoạt Xa (Bẫy)",
        group: "PHI ĐAO",
        desc: "Bẫy phế xe kinh điển để tranh tiên.",
        moves: [
            [7, 7, 4, 7], [1, 0, 2, 2], [1, 9, 2, 7], [0, 0, 1, 0],
            [8, 9, 7, 9], [7, 0, 6, 2], [2, 6, 2, 5], [2, 3, 2, 4],
            [7, 9, 7, 5], [1, 2, 0, 2], [7, 5, 3, 5], [0, 2, 0, 3],
            [3, 5, 3, 3], [3, 0, 4, 1], [7, 7, 4, 7]
        ]
    },
    {
        name: "Quy Bối Pháo",
        group: "PHI ĐAO",
        desc: "Lùi Pháo về sau Mã để phòng thủ phản công.",
        moves: [
            [7, 7, 4, 7], [1, 0, 2, 2], [1, 9, 2, 7], [0, 0, 1, 0],
            [8, 9, 7, 9], [1, 2, 2, 2], [7, 9, 7, 8], [1, 2, 0, 2],
            [7, 8, 2, 8], [0, 2, 1, 2]
        ]
    }
];

/**
 * @description  Bootstrap the library.
 */
export const learn = (): void => {
    // Helper to execute move and store in book
    const play = (line: number[][]) => {
        const sandbox = new Int8Array(genesis());
        let currentHash = compute(sandbox, Side.Red);
        let currentTurn: Side = Side.Red;

        for (const step of line) {
            const [fx, fy, tx, ty] = step;
            const source = flatten(fx, fy);
            const target = flatten(tx, ty);
            
            // Safety check: Don't learn impossible moves
            if (sandbox[source] === 0) break; 

            const move = (source << 8) | target;
            
            // Priority: Keep existing (Main lines are defined first)
            if (!BOOK.has(currentHash)) {
                BOOK.set(currentHash, move);
            }

            const captured = commit(sandbox, source, target);
            currentHash = modify(currentHash, sandbox, move, captured);
            currentTurn = currentTurn === Side.Red ? Side.Black : Side.Red;
        }
    };

    OPENINGS.forEach(op => play(op.moves));
    console.log(`[A.R.E.S] Library Loaded: ${BOOK.size} grandmaster positions.`);
};

export const consult = (hash: bigint): number => {
    const id = hash.toString(16);
    if (KNOWLEDGE[id]) return KNOWLEDGE[id];
    return BOOK.get(hash) || 0;
};
